version: "3.9"
services:
  # web:
  #   build:
  #     dockerfile: Dockerfile
  #     context: ./packages/web/
  #     target: development
  #   volumes:
  #     - .:/usr/src/web
  #   ports:
  #     - "8080:8080"
  #     - "8081:8081"
  #   depends_on:
  #     - "api"
  api:
    build:
      dockerfile: Dockerfile
      context: ./packages/api/
      target: development
    volumes:
      - .:/usr/src/app
    env_file:
      - ./packages/api/.env
    ports:
      - 3000:3000
    command: bash -c "
      npx prisma migrate dev &&
      npx prisma generate &&
      nest start --watch"
    depends_on:
      - "db"
  db:
    build: ./packages/db/
    image: postgres
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "$DB_PORT:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
    driver: local
