services:
  api:
    build:
      dockerfile: Dockerfile
      context: ./packages/api/
      target: production
    volumes:
      - .:/usr/src/app
    env_file:
      - ./packages/api/.env
    command: npm run start:prod
    ports:
      - 3000:3000
    depends_on:
      - "db"
  db:
    build: ./packages/db/
    image: postgres
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
