version: "3.9"
services:
  web:
    build:
      dockerfile: Dockerfile
      context: ./packages/web/
      target: development
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - "api"
  api:
    build:
      dockerfile: Dockerfile
      context: ./packages/api/
      target: development
    env_file:
      - ./packages/api/.env
    ports:
      - 3000:3000
    depends_on:
      - "db"
  db:
    build: ./packages/db/
    image: postgres
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: yt
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
    ports:
      - "6565:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
    driver: local
