import "./globals.css";

import { Navbar } from "@/components";
import Providers from "./Providers";
import { ModalsPortal } from "./ModalsPortal";
import { AlertsPortal } from "./AlertsPortal";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="relative">
        <Providers>
          <Navbar />
          {children}
          <ModalsPortal></ModalsPortal>
          <AlertsPortal></AlertsPortal>
        </Providers>
      </body>
    </html>
  );
}
